'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThirdwebProvider } from '@thirdweb-dev/react'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

const activeChain = 'mumbai'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider activeChain={activeChain}>
          <Navbar />
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  )
}
